name: Release package

on:
    workflow_run:
        workflows: [Run Tests]
        types: [completed]
        branches: [master]

permissions:
    contents: write
    pull-requests: write

jobs:
    release-if-needed:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - name: Create Release PR
              uses: google-github-actions/release-please-action@v4
              id: release
              with:
                  release-type: php

            - name: Checkout
              uses: actions/checkout@v4

            - name: Update version in Honeybadger.php
              if: ${{ steps.release.outputs.release_created }}
              run: php scripts/SyncSourceCodeWithPackageVersion.php ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}

            - uses: stefanzweifel/git-auto-commit-action@v5
              if: ${{ steps.release.outputs.release_created }}
              with:
                commit_message: "[skip ci] chore: update version to ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
                commit_user_name: "honeybadger-robot"
                commit_user_email: "honeybadger-robot@honeybadger.io"
