name: Run Tests

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        composer-flags: ["--prefer-stable", "--prefer-lowest"]
        php-versions: ['7.3', '7.4']
    name: PHP ${{ matrix.php-versions }} Tests (${{ matrix.composer-flags }})
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none
        tools: phpunit

    - name: Install dependencies
      run: composer update ${{ matrix.composer-flags }} --no-interaction
  
    - name: Run Tests
      run: vendor/bin/phpunit
